workflows:
  default-workflow:
    name: Build APK for Rewan
    environment:
      flutter: stable
      groups:
        - keystore
    scripts:
      - name: Decode keystore
        script: echo $CM_KEYSTORE | base64 --decode > rewan_keystore.jks
      - name: Build APK
        script: |
          flutter pub get
          flutter build apk --release --no-shrink
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
