name: rewan
description: تطبيق Rewan لربح النقاط والإعلانات والسحب.

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.8.3
  firebase_messaging: ^14.6.9
  google_mobile_ads: ^3.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^15.1.0+1
  url_launcher: ^6.2.6
  percent_indicator: ^4.2.3
  flutter_chat_ui: ^1.6.7
  flutter_chat_types: ^3.6.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
